name: Build, Test & Publish
on: [push]
jobs:
  Build-Test-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      #- name: Remove -SNAPSHOT suffix from bee-built version
      #  run: sed -i '/bee-built/ s/-SNAPSHOT//g' ./gradle/libs.versions.toml
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Make gradlew executable
        run: |
          chmod +x ./bee.persistent/gradlew
          chmod +x ./bee.functional/gradlew
          chmod +x ./bee.buzz/gradlew
          chmod +x ./bee.generative/gradlew
          chmod +x ./bee.fetched/gradlew
          chmod +x ./bee.fetched.test/gradlew
          chmod +x ./example/application/gradlew
      - name: Build & Test bee.persistent
        working-directory: ./bee.persistent
        run: ./gradlew build
      - name: Build & Test bee.functional
        working-directory: ./bee.functional
        run: ./gradlew build
      - name: Build & Test bee.buzz
        working-directory: ./bee.buzz
        run: ./gradlew build
      - name: Build & Test bee.generative
        working-directory: ./bee.generative
        run: ./gradlew build
      - name: Build & Test bee.fetched
        run: |
          cd ./bee.fetched/
          ./gradlew build
          cd ../bee.fetched.test/
          ./gradlew build
      - name: Build & Test example application
        working-directory: ./example/application
        run: ./gradlew build

          
